{
	"version": 1740138505,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/pepe-sheet0.png",
		"images/bg-sheet0.png",
		"images/whale-sheet0.png",
		"images/border-sheet0.png",
		"images/l1-sheet0.png",
		"images/sky-sheet0.png",
		"images/sky2-sheet0.png",
		"images/diamond-sheet0.png",
		"images/particlescoins.png",
		"images/particlesgems.png",
		"images/powershieldring-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/collect diamond.m4a",
		"media/collect diamond.ogg",
		"media/game over (2).m4a",
		"media/game over (2).ogg",
		"media/coin collect.m4a",
		"media/coin collect.ogg",
		"media/whale sound.m4a",
		"media/whale sound.ogg",
		"media/bg (1).m4a",
		"media/bg (1).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}